ALTER TABLE "News" RENAME COLUMN "title" TO "titleRu";
ALTER TABLE "News" RENAME COLUMN "description" TO "descriptionRu";
ALTER TABLE "News" RENAME COLUMN "content" TO "contentRu";

ALTER TABLE "News"
ADD COLUMN "titleKz" VARCHAR(240) NOT NULL DEFAULT '',
ADD COLUMN "descriptionKz" VARCHAR(800) NOT NULL DEFAULT '',
ADD COLUMN "contentKz" TEXT NOT NULL DEFAULT '';

ALTER TABLE "News" ALTER COLUMN "titleKz" DROP DEFAULT;
ALTER TABLE "News" ALTER COLUMN "descriptionKz" DROP DEFAULT;
ALTER TABLE "News" ALTER COLUMN "contentKz" DROP DEFAULT;
