import { useCallback, useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, ShieldCheck } from 'lucide-react';
import api, { apiMessage } from '../../api/client.js';
import AdminPageHeader from '../../components/admin/AdminPageHeader.jsx';
import { ErrorState, LoadingState } from '../../components/common/States.jsx';
import { useAdminI18n } from '../../utils/adminLocalization.js';

const actions = ['LOGIN', 'LOGOUT', 'CREATE_SERVICE', 'UPDATE_SERVICE', 'DELETE_SERVICE', 'CREATE_CATEGORY', 'UPDATE_CATEGORY', 'DELETE_CATEGORY', 'CREATE_NEWS', 'UPDATE_NEWS', 'DELETE_NEWS', 'PUBLISH_NEWS', 'UNPUBLISH_NEWS', 'CREATE_ADMIN', 'UPDATE_ADMIN', 'DELETE_ADMIN', 'UPDATE_SETTINGS'];
export default function AuditLogsPage() {
  const { locale, tr } = useAdminI18n();
  const [rows, setRows] = useState(null); const [meta, setMeta] = useState({ page: 1, pages: 1 }); const [filters, setFilters] = useState({ page: 1, action: '' }); const [error, setError] = useState('');
  const load = useCallback(async () => { setError(''); try { const response = await api.get('/admin/audit-logs', { params: { ...filters, limit: 30 } }); setRows(response.data.data); setMeta(response.data.meta); } catch (err) { setError(apiMessage(err)); } }, [filters]);
  useEffect(() => { load(); }, [load]);
  return <><AdminPageHeader eyebrow="Безопасность" eyebrowKz="Қауіпсіздік" title="Журнал действий" titleKz="Әрекеттер журналы" description="Неизменяемая история административных операций" descriptionKz="Әкімшілік операциялардың өзгермейтін тарихы" actions={<label className="action-filter"><ShieldCheck /><select value={filters.action} onChange={(e) => setFilters({ action: e.target.value, page: 1 })}><option value="">{tr('Все действия')}</option>{actions.map((action) => <option value={action} key={action}>{tr(action)}</option>)}</select></label>} />{error ? <ErrorState title={tr('Не удалось загрузить журнал', 'Журналды жүктеу мүмкін болмады')} text={error} onRetry={load} /> : !rows ? <LoadingState /> : <div className="admin-card admin-table-wrap"><table className="admin-table"><thead><tr><th>{tr('Дата')}</th><th>{tr('Сотрудник')}</th><th>{tr('Действие')}</th><th>{tr('Объект')}</th><th>IP</th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td>{new Date(item.createdAt).toLocaleString(locale)}</td><td><strong>{item.adminUser.fullName}</strong><small className="table-subline">{item.adminUser.login}</small></td><td><span className="status-pill status-pill--neutral">{tr(item.action)}</span></td><td>{tr(item.entityType) || '—'} {item.entityId ? `#${item.entityId}` : ''}</td><td>{item.ipAddress || '—'}</td></tr>)}</tbody></table></div>}{meta.pages > 1 && <div className="pagination"><button disabled={meta.page <= 1} onClick={() => setFilters({ ...filters, page: meta.page - 1 })}><ChevronLeft />{tr('Назад')}</button><span>{tr('Страница', 'Бет')} {meta.page} {tr('из', 'ішінен')} {meta.pages}</span><button disabled={meta.page >= meta.pages} onClick={() => setFilters({ ...filters, page: meta.page + 1 })}>{tr('Далее')}<ChevronRight /></button></div>}</>;
}
