import { useCallback, useEffect, useState } from 'react';
import { Cake, Edit3, Film, Plus, Save, Trash2, Upload, Video } from 'lucide-react';
import api, { apiMessage, assetUrl } from '../../api/client.js';
import AdminPageHeader from '../../components/admin/AdminPageHeader.jsx';
import Toast from '../../components/admin/Toast.jsx';
import { ConfirmDialog, Modal } from '../../components/admin/Modal.jsx';
import { ErrorState, LoadingState } from '../../components/common/States.jsx';
import { useAuth } from '../../context/AuthContext.jsx';

const blank = { type: 'BIRTHDAY', titleRu: '', titleKz: '', descriptionRu: '', descriptionKz: '', mediaUrl: '', eventDate: '', isActive: true, sortOrder: 0 };
const toForm = (item) => ({ ...item, mediaUrl: item.mediaUrl || '', eventDate: item.eventDate ? new Date(item.eventDate).toISOString().slice(0, 10) : '' });

function ItemForm({ form, setForm, onSubmit, onCancel, onUpload, uploading, busy, error }) {
  const birthday = form.type === 'BIRTHDAY';
  return <form className="admin-form" onSubmit={onSubmit}><div className="form-grid">
    <label><span>Тип слайда</span><select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value, mediaUrl: '', eventDate: '' })}><option value="BIRTHDAY">День рождения</option><option value="VIDEO">Видео</option></select></label>
    <label><span>Порядок</span><input type="number" min="0" max="10000" value={form.sortOrder} onChange={(event) => setForm({ ...form, sortOrder: Number(event.target.value) })} /></label>
    <label><span>{birthday ? 'Имя сотрудника (русский)' : 'Название видео (русский)'}</span><input required maxLength="240" value={form.titleRu} onChange={(event) => setForm({ ...form, titleRu: event.target.value })} /></label>
    <label><span>{birthday ? 'Қызметкердің аты-жөні (қазақша)' : 'Видео атауы (қазақша)'}</span><input required maxLength="240" value={form.titleKz} onChange={(event) => setForm({ ...form, titleKz: event.target.value })} /></label>
    <label><span>{birthday ? 'Должность и поздравление (русский)' : 'Описание (русский)'}</span><textarea required maxLength="1200" value={form.descriptionRu} onChange={(event) => setForm({ ...form, descriptionRu: event.target.value })} /></label>
    <label><span>{birthday ? 'Лауазымы және құттықтау (қазақша)' : 'Сипаттама (қазақша)'}</span><textarea required maxLength="1200" value={form.descriptionKz} onChange={(event) => setForm({ ...form, descriptionKz: event.target.value })} /></label>
    {birthday ? <label><span>Дата рождения</span><input required type="date" value={form.eventDate} onChange={(event) => setForm({ ...form, eventDate: event.target.value })} /><small>Год на публичном экране не показывается.</small></label> : <label className="form-grid__wide"><span>Видеофайл</span><span className="image-upload-control"><Upload size={20} />{uploading ? 'Загрузка…' : form.mediaUrl ? 'Заменить видео' : 'Загрузить видео'}<input type="file" accept="video/mp4,video/webm" onChange={onUpload} disabled={uploading} /></span><small>MP4 или WebM, до 150 МБ. Видео воспроизводится автоматически без звука.</small>{form.mediaUrl && <video className="broadcast-video-preview" src={assetUrl(form.mediaUrl)} controls muted />}</label>}
    <label className="toggle-label form-grid__wide"><input type="checkbox" checked={form.isActive} onChange={(event) => setForm({ ...form, isActive: event.target.checked })} /><span>Показывать в эфире</span></label>
  </div>{error && <div className="form-error">{error}</div>}<div className="form-actions"><button type="button" className="admin-button admin-button--secondary" onClick={onCancel}>Отмена</button><button className="admin-button admin-button--primary" disabled={busy || uploading || (!birthday && !form.mediaUrl)}>{busy ? 'Сохранение…' : 'Сохранить'}</button></div></form>;
}

export default function BroadcastPage() {
  const { user } = useAuth(); const canDelete = ['SUPER_ADMIN', 'ADMIN'].includes(user.role);
  const [settings, setSettings] = useState(null); const [items, setItems] = useState(null); const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null);
  const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState(''); const [toast, setToast] = useState(null);
  const load = useCallback(async () => { setError(''); try { const [settingsResponse, itemsResponse] = await Promise.all([api.get('/admin/broadcast/settings'), api.get('/admin/broadcast/items')]); setSettings(settingsResponse.data.data); setItems(itemsResponse.data.data); } catch (err) { setError(apiMessage(err)); } }, []);
  useEffect(() => { load(); }, [load]);
  const saveSettings = async (event) => { event.preventDefault(); setBusy(true); try { const response = await api.patch('/admin/broadcast/settings', settings); setSettings(response.data.data); setToast({ message: 'Настройки эфира сохранены' }); } catch (err) { setToast({ type: 'error', message: apiMessage(err) }); } finally { setBusy(false); } };
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(''); try { const data = new FormData(); data.append('video', file); const response = await api.post('/admin/broadcast/videos', data); setEditing((current) => ({ ...current, mediaUrl: response.data.data.path })); } catch (err) { setError(apiMessage(err)); } finally { setUploading(false); event.target.value = ''; } };
  const saveItem = async (event) => { event.preventDefault(); setBusy(true); setError(''); const id = editing.id; const payload = { type: editing.type, titleRu: editing.titleRu, titleKz: editing.titleKz, descriptionRu: editing.descriptionRu, descriptionKz: editing.descriptionKz, mediaUrl: editing.type === 'VIDEO' ? editing.mediaUrl : null, eventDate: editing.type === 'BIRTHDAY' ? editing.eventDate : null, isActive: editing.isActive, sortOrder: editing.sortOrder }; try { if (id) await api.patch(`/admin/broadcast/items/${id}`, payload); else await api.post('/admin/broadcast/items', payload); setEditing(null); setToast({ message: id ? 'Слайд обновлён' : 'Слайд создан' }); await load(); } catch (err) { setError(apiMessage(err)); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); try { await api.delete(`/admin/broadcast/items/${deleting.id}`); setDeleting(null); setToast({ message: 'Слайд удалён' }); await load(); } catch (err) { setToast({ type: 'error', message: apiMessage(err) }); } finally { setBusy(false); } };
  if (!settings || !items) return error ? <ErrorState title="Не удалось загрузить эфир" text={error} onRetry={load} /> : <LoadingState />;
  return <><AdminPageHeader eyebrow="Контент" title="Эфир" description="Полноэкранные слайды, дни рождения, видео и бегущая строка" actions={<button className="admin-button admin-button--primary" onClick={() => setEditing({ ...blank })}><Plus size={19} />Добавить слайд</button>} />
    <form className="admin-card broadcast-settings" onSubmit={saveSettings}><header><Film /><div><h2>Бегущая строка и автоматика</h2><p>Каждый слайд сначала показывается на казахском, затем на русском</p></div></header><div className="form-grid"><label className="form-grid__wide"><span>Бегущая строка — русский</span><textarea required maxLength="1000" value={settings.tickerTextRu} onChange={(event) => setSettings({ ...settings, tickerTextRu: event.target.value })} /></label><label className="form-grid__wide"><span>Бегущая строка — қазақша</span><textarea required maxLength="1000" value={settings.tickerTextKz} onChange={(event) => setSettings({ ...settings, tickerTextKz: event.target.value })} /></label><label><span>Полный цикл слайда, секунд</span><input type="number" min="12" max="240" value={settings.broadcastSlideSeconds} onChange={(event) => setSettings({ ...settings, broadcastSlideSeconds: Number(event.target.value) })} /><small>Казахская и русская версии вместе.</small></label><label><span>Смена на русский через, секунд</span><input type="number" min="5" max="120" value={settings.broadcastLanguageSeconds} onChange={(event) => setSettings({ ...settings, broadcastLanguageSeconds: Number(event.target.value) })} /></label><label><span>Возврат в эфир через, секунд</span><input type="number" min="15" max="1800" value={settings.broadcastIdleSeconds} onChange={(event) => setSettings({ ...settings, broadcastIdleSeconds: Number(event.target.value) })} /><small>После последнего касания в обычной ленте.</small></label></div><button className="admin-button admin-button--primary" disabled={busy}><Save size={18} />Сохранить настройки</button></form>
    <section className="admin-card admin-table-wrap"><table className="admin-table"><thead><tr><th>Слайд</th><th>Тип</th><th>Условие показа</th><th>Статус</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><div className="table-title"><span>{item.type === 'BIRTHDAY' ? <Cake /> : <Video />}</span><div><strong>{item.titleRu}</strong><small>{item.titleKz}</small></div></div></td><td>{item.type === 'BIRTHDAY' ? 'День рождения' : 'Видео'}</td><td>{item.type === 'BIRTHDAY' && item.eventDate ? new Date(item.eventDate).toLocaleDateString('ru-RU', { day: 'numeric', month: 'long' }) : 'Всегда'}</td><td><span className={`status-pill ${item.isActive ? 'status-pill--success' : 'status-pill--muted'}`}>{item.isActive ? 'В эфире' : 'Отключён'}</span></td><td><div className="row-actions"><button onClick={() => setEditing(toForm(item))} aria-label="Редактировать"><Edit3 /></button>{canDelete && <button onClick={() => setDeleting(item)} aria-label="Удалить"><Trash2 /></button>}</div></td></tr>)}</tbody></table></section>
    {editing && <Modal title={editing.id ? 'Редактирование слайда' : 'Новый слайд'} onClose={() => setEditing(null)} wide><ItemForm form={editing} setForm={setEditing} onSubmit={saveItem} onCancel={() => setEditing(null)} onUpload={upload} uploading={uploading} busy={busy} error={error} /></Modal>}
    {deleting && <ConfirmDialog title="Удалить слайд?" text={`«${deleting.titleRu}» будет удалён без возможности восстановления.`} onConfirm={remove} onCancel={() => setDeleting(null)} busy={busy} />}
    <Toast {...toast} onClose={() => setToast(null)} /></>;
}
