import { useCallback, useEffect, useState } from 'react';
import { Edit3, Plus, Search, Trash2 } from 'lucide-react';
import api, { apiMessage } from '../../api/client.js';
import AdminPageHeader from '../../components/admin/AdminPageHeader.jsx';
import Toast from '../../components/admin/Toast.jsx';
import { ConfirmDialog, Modal } from '../../components/admin/Modal.jsx';
import { ErrorState, LoadingState } from '../../components/common/States.jsx';
import AppIcon from '../../components/common/AppIcon.jsx';
import { useAuth } from '../../context/AuthContext.jsx';

const blank = { slug: '', titleRu: '', titleKz: '', descriptionRu: '', descriptionKz: '', icon: 'Folder', isPublished: true, sortOrder: 0 };
const icons = ['Folder', 'Users', 'BriefcaseBusiness', 'Building2', 'Landmark', 'Car', 'CircleDollarSign', 'FileText', 'Files', 'ReceiptText', 'Container', 'CalendarClock', 'MessagesSquare'];
export default function CategoriesPage() {
  const { user } = useAuth(); const [rows, setRows] = useState(null); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null); const [busy, setBusy] = useState(false); const [toast, setToast] = useState(null);
  const canCreateDelete = ['SUPER_ADMIN', 'ADMIN'].includes(user.role);
  const load = useCallback(async () => { setError(''); try { const response = await api.get('/admin/categories', { params: { search, limit: 100, sort: 'sortOrder', direction: 'asc' } }); setRows(response.data.data); } catch (err) { setError(apiMessage(err)); } }, [search]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  const save = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { if (editing.id) await api.patch(`/admin/categories/${editing.id}`, editing); else await api.post('/admin/categories', editing); setEditing(null); setToast({ type: 'success', message: editing.id ? 'Категория обновлена' : 'Категория создана' }); await load(); } catch (err) { setError(apiMessage(err)); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); try { await api.delete(`/admin/categories/${deleting.id}`); setDeleting(null); setToast({ type: 'success', message: 'Категория удалена' }); await load(); } catch (err) { setToast({ type: 'error', message: apiMessage(err) }); setDeleting(null); } finally { setBusy(false); } };
  return <><AdminPageHeader eyebrow="Контент" title="Категории услуг" description="Структура каталога на русском и казахском языках" actions={canCreateDelete && <button className="admin-button admin-button--primary" onClick={() => setEditing({ ...blank })}><Plus size={19} />Новая категория</button>} /><div className="admin-toolbar"><label className="admin-search"><Search /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Поиск по названию или slug" /></label><span>{rows?.length || 0} записей</span></div>{error && !editing && <ErrorState title="Не удалось загрузить категории" text={error} onRetry={load} />}{!rows && !error ? <LoadingState /> : rows && <div className="admin-card admin-table-wrap"><table className="admin-table"><thead><tr><th>Порядок</th><th>Категория</th><th>Қазақша</th><th>Услуги</th><th>Статус</th><th></th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td>{item.sortOrder}</td><td><div className="table-title"><span><AppIcon name={item.icon} size={22} /></span><div><strong>{item.titleRu}</strong><small>{item.slug}</small></div></div></td><td>{item.titleKz}</td><td>{item._count.services}</td><td><span className={`status-pill ${item.isPublished ? 'status-pill--success' : 'status-pill--muted'}`}>{item.isPublished ? 'Опубликована' : 'Скрыта'}</span></td><td><div className="row-actions"><button onClick={() => setEditing({ ...item })} aria-label="Редактировать"><Edit3 /></button>{canCreateDelete && <button onClick={() => setDeleting(item)} aria-label="Удалить"><Trash2 /></button>}</div></td></tr>)}</tbody></table></div>}
    {editing && <Modal title={editing.id ? 'Редактирование категории' : 'Новая категория'} onClose={() => setEditing(null)}><form className="admin-form" onSubmit={save}><div className="form-grid"><label><span>Название (русский)</span><input required maxLength={160} value={editing.titleRu} onChange={(e) => setEditing({ ...editing, titleRu: e.target.value })} /></label><label><span>Название (қазақша)</span><input required maxLength={160} value={editing.titleKz} onChange={(e) => setEditing({ ...editing, titleKz: e.target.value })} /></label><label className="form-grid__wide"><span>Slug</span><input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxLength={120} value={editing.slug} onChange={(e) => setEditing({ ...editing, slug: e.target.value.toLowerCase() })} /></label><label><span>Описание (русский)</span><textarea required maxLength={600} value={editing.descriptionRu} onChange={(e) => setEditing({ ...editing, descriptionRu: e.target.value })} /></label><label><span>Описание (қазақша)</span><textarea required maxLength={600} value={editing.descriptionKz} onChange={(e) => setEditing({ ...editing, descriptionKz: e.target.value })} /></label><fieldset className="form-grid__wide"><legend>Иконка</legend><div className="icon-picker">{icons.map((icon) => <button type="button" className={editing.icon === icon ? 'selected' : ''} onClick={() => setEditing({ ...editing, icon })} key={icon}><AppIcon name={icon} /><span>{icon}</span></button>)}</div></fieldset><label><span>Порядок</span><input type="number" min="0" max="10000" required value={editing.sortOrder} onChange={(e) => setEditing({ ...editing, sortOrder: Number(e.target.value) })} /></label><label className="toggle-label"><input type="checkbox" checked={editing.isPublished} onChange={(e) => setEditing({ ...editing, isPublished: e.target.checked })} /><span>Опубликована</span></label></div>{error && <div className="form-error">{error}</div>}<div className="form-actions"><button type="button" className="admin-button admin-button--secondary" onClick={() => setEditing(null)}>Отмена</button><button className="admin-button admin-button--primary" disabled={busy}>{busy ? 'Сохранение…' : 'Сохранить'}</button></div></form></Modal>}
    {deleting && <ConfirmDialog title="Удалить категорию?" text={`Категория «${deleting.titleRu}» будет удалена. Если в ней есть услуги, система не позволит выполнить операцию.`} onConfirm={remove} onCancel={() => setDeleting(null)} busy={busy} />}<Toast {...toast} onClose={() => setToast(null)} />
  </>;
}
