import { useState } from 'react';
import { Eye, EyeOff, LockKeyhole, LogIn, ShieldCheck, UserRound } from 'lucide-react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext.jsx';
import { apiMessage } from '../../api/client.js';

export default function LoginPage() {
  const { user, login, ready } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [show, setShow] = useState(false); const [form, setForm] = useState({ login: '', password: '' }); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  if (ready && user) return <Navigate to="/admin" replace />;
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); setError(''); try { await login(form); navigate(location.state?.from || '/admin', { replace: true }); } catch (err) { setError(apiMessage(err, 'Не удалось войти')); } finally { setSubmitting(false); } };
  return <main className="login-page"><section className="login-panel"><div className="login-panel__brand"><span>ДГД</span><ShieldCheck size={32} /></div><div className="login-panel__intro"><span>Защищённый доступ</span><h1>Панель управления инфокиоском</h1><p>Для сотрудников Департамента государственных доходов по городу Алматы</p></div><form onSubmit={submit} className="login-form"><label><span>Логин</span><div><UserRound size={21} /><input required maxLength={80} autoComplete="username" value={form.login} onChange={(e) => setForm({ ...form, login: e.target.value })} /></div></label><label><span>Пароль</span><div><LockKeyhole size={21} /><input required minLength={8} maxLength={128} type={show ? 'text' : 'password'} autoComplete="current-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><button type="button" onClick={() => setShow(!show)} aria-label={show ? 'Скрыть пароль' : 'Показать пароль'}>{show ? <EyeOff /> : <Eye />}</button></div></label>{error && <div className="form-error" role="alert">{error}</div>}<button className="admin-button admin-button--primary" disabled={submitting}>{submitting ? 'Проверка…' : 'Войти'}<LogIn size={20} /></button></form><small>Все действия в системе регистрируются в журнале безопасности.</small></section><section className="login-visual"><div className="login-visual__seal"><ShieldCheck size={68} /><span>ДГД</span></div><h2>Управляйте информацией централизованно</h2><ul><li>Двуязычный каталог услуг</li><li>Обезличенная аналитика</li><li>Контроль публикаций и ролей</li></ul></section></main>;
}
