import { useState } from 'react';
import { Eye, EyeOff, Languages, LockKeyhole, LogIn, ShieldCheck, UserRound } from 'lucide-react';
import { Navigate, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext.jsx';
import { apiMessage } from '../../api/client.js';
import { useAdminI18n } from '../../utils/adminLocalization.js';
import DgdLogo from '../../components/common/DgdLogo.jsx';

export default function LoginPage() {
  const { user, login, ready } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [show, setShow] = useState(false); const [form, setForm] = useState({ login: '', password: '' }); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false);
  const { language, tr, toggleLanguage } = useAdminI18n();
  if (ready && user) return <Navigate to="/admin" replace />;
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); setError(''); try { await login(form); navigate(location.state?.from || '/admin', { replace: true }); } catch (err) { setError(apiMessage(err, tr('Не удалось войти', 'Кіру мүмкін болмады'))); } finally { setSubmitting(false); } };
  return <main className="login-page"><button type="button" className="login-language-switch" onClick={toggleLanguage}><Languages size={19} />{language === 'kz' ? 'Русский' : 'Қазақша'}</button><section className="login-panel"><div className="login-panel__brand"><DgdLogo className="login-brand-logo" /><ShieldCheck size={32} /></div><div className="login-panel__intro"><span>{tr('Защищённый доступ', 'Қорғалған қолжетімділік')}</span><h1>{tr('Панель управления инфокиоском', 'Инфокиоскіні басқару панелі')}</h1><p>{tr('Для сотрудников Департамента государственных доходов по городу Алматы', 'Алматы қаласы бойынша Мемлекеттік кірістер департаментінің қызметкерлеріне арналған')}</p></div><form onSubmit={submit} className="login-form"><label><span>{tr('Логин')}</span><div><UserRound size={21} /><input required maxLength={80} autoComplete="username" value={form.login} onChange={(e) => setForm({ ...form, login: e.target.value })} /></div></label><label><span>{tr('Пароль')}</span><div><LockKeyhole size={21} /><input required minLength={8} maxLength={128} type={show ? 'text' : 'password'} autoComplete="current-password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><button type="button" onClick={() => setShow(!show)} aria-label={show ? tr('Скрыть пароль', 'Құпиясөзді жасыру') : tr('Показать пароль', 'Құпиясөзді көрсету')}>{show ? <EyeOff /> : <Eye />}</button></div></label>{error && <div className="form-error" role="alert">{tr(error)}</div>}<button className="admin-button admin-button--primary" disabled={submitting}>{submitting ? tr('Проверка…', 'Тексерілуде…') : tr('Войти', 'Кіру')}<LogIn size={20} /></button></form><small>{tr('Все действия в системе регистрируются в журнале безопасности.', 'Жүйедегі барлық әрекет қауіпсіздік журналында тіркеледі.')}</small></section><section className="login-visual"><div className="login-visual__seal"><DgdLogo className="login-seal-logo" /></div><h2>{tr('Управляйте информацией централизованно', 'Ақпаратты орталықтандырылған түрде басқарыңыз')}</h2><ul><li>{tr('Двуязычный каталог услуг', 'Екі тілдегі қызметтер каталогы')}</li><li>{tr('Обезличенная аналитика', 'Дербестендірілмеген талдау')}</li><li>{tr('Контроль публикаций и ролей', 'Жарияланымдар мен рөлдерді бақылау')}</li></ul></section></main>;
}
