import { useCallback, useEffect, useState } from 'react';
import { Edit3, Plus, Search, ShieldCheck, Trash2 } from 'lucide-react';
import api, { apiMessage } from '../../api/client.js';
import AdminPageHeader from '../../components/admin/AdminPageHeader.jsx';
import Toast from '../../components/admin/Toast.jsx';
import { ConfirmDialog, Modal } from '../../components/admin/Modal.jsx';
import { LoadingState } from '../../components/common/States.jsx';
import { useAdminI18n } from '../../utils/adminLocalization.js';

const blank = { login: '', password: '', fullName: '', role: 'EDITOR', isActive: true };
export default function UsersPage() {
  const { locale, tr } = useAdminI18n();
  const [rows, setRows] = useState(null); const [search, setSearch] = useState(''); const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null); const [busy, setBusy] = useState(false); const [toast, setToast] = useState(null); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const response = await api.get('/admin/users', { params: { search, limit: 100 } }); setRows(response.data.data); } catch (err) { setToast({ type: 'error', message: apiMessage(err) }); } }, [search]);
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [load]);
  const save = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const body = { ...editing }; if (editing.id && !body.password) delete body.password; if (editing.id) await api.patch(`/admin/users/${editing.id}`, body); else await api.post('/admin/users', body); setEditing(null); setToast({ message: editing.id ? tr('Данные администратора обновлены', 'Әкімші деректері жаңартылды') : tr('Администратор создан', 'Әкімші құрылды') }); await load(); } catch (err) { setError(apiMessage(err)); } finally { setBusy(false); } };
  const remove = async () => { setBusy(true); try { await api.delete(`/admin/users/${deleting.id}`); setDeleting(null); setToast({ message: tr('Администратор удалён', 'Әкімші жойылды') }); await load(); } catch (err) { setDeleting(null); setToast({ type: 'error', message: apiMessage(err) }); } finally { setBusy(false); } };
  return <><AdminPageHeader eyebrow="Безопасность" eyebrowKz="Қауіпсіздік" title="Администраторы" titleKz="Әкімшілер" description="Учётные записи, роли и доступ к панели управления" descriptionKz="Тіркелгілер, рөлдер және басқару панеліне қолжетімділік" actions={<button className="admin-button admin-button--primary" onClick={() => setEditing({ ...blank })}><Plus size={19} />{tr('Добавить администратора', 'Әкімші қосу')}</button>} /><div className="admin-toolbar"><label className="admin-search"><Search /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={tr('Поиск по имени или логину', 'Аты немесе логин бойынша іздеу')} /></label></div>{!rows ? <LoadingState /> : <div className="admin-card admin-table-wrap"><table className="admin-table"><thead><tr><th>{tr('Сотрудник')}</th><th>{tr('Роль')}</th><th>{tr('Статус')}</th><th>{tr('Последний вход')}</th><th>{tr('Создан')}</th><th></th></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><div className="table-title"><span><ShieldCheck size={22} /></span><div><strong>{item.fullName}</strong><small>{item.login}</small></div></div></td><td><span className="status-pill status-pill--neutral">{item.role}</span></td><td><span className={`status-pill ${item.isActive ? 'status-pill--success' : 'status-pill--danger'}`}>{item.isActive ? tr('Активен') : tr('Заблокирован')}</span></td><td>{item.lastLoginAt ? new Date(item.lastLoginAt).toLocaleString(locale) : tr('Не входил')}</td><td>{new Date(item.createdAt).toLocaleDateString(locale)}</td><td><div className="row-actions"><button aria-label={tr('Редактировать', 'Өңдеу')} onClick={() => setEditing({ ...item, password: '' })}><Edit3 /></button><button aria-label={tr('Удалить')} onClick={() => setDeleting(item)}><Trash2 /></button></div></td></tr>)}</tbody></table></div>}
    {editing && <Modal title={editing.id ? 'Редактирование администратора' : 'Новый администратор'} titleKz={editing.id ? 'Әкімшіні өңдеу' : 'Жаңа әкімші'} onClose={() => setEditing(null)}><form className="admin-form" onSubmit={save}><div className="form-grid"><label><span>{tr('ФИО')}</span><input required maxLength={160} value={editing.fullName} onChange={(e) => setEditing({ ...editing, fullName: e.target.value })} /></label><label><span>{tr('Логин')}</span><input required maxLength={80} value={editing.login} onChange={(e) => setEditing({ ...editing, login: e.target.value })} /></label><label><span>{editing.id ? tr('Новый пароль (необязательно)', 'Жаңа құпиясөз (міндетті емес)') : tr('Пароль')}</span><input type="password" required={!editing.id} minLength={10} maxLength={128} value={editing.password} onChange={(e) => setEditing({ ...editing, password: e.target.value })} /></label><label><span>{tr('Роль')}</span><select value={editing.role} onChange={(e) => setEditing({ ...editing, role: e.target.value })}><option>EDITOR</option><option>ADMIN</option><option>SUPER_ADMIN</option></select></label><label className="toggle-label form-grid__wide"><input type="checkbox" checked={editing.isActive} onChange={(e) => setEditing({ ...editing, isActive: e.target.checked })} /><span>{tr('Учётная запись активна', 'Тіркелгі белсенді')}</span></label></div>{error && <div className="form-error">{tr(error)}</div>}<div className="form-actions"><button type="button" className="admin-button admin-button--secondary" onClick={() => setEditing(null)}>{tr('Отмена')}</button><button className="admin-button admin-button--primary" disabled={busy}>{busy ? tr('Сохранение…') : tr('Сохранить')}</button></div></form></Modal>}
    {deleting && <ConfirmDialog title="Удалить администратора?" titleKz="Әкімшіні жою керек пе?" text={`Учётная запись «${deleting.fullName}» будет удалена без возможности восстановления.`} textKz={`«${deleting.fullName}» тіркелгісі қалпына келтіру мүмкіндігінсіз жойылады.`} onConfirm={remove} onCancel={() => setDeleting(null)} busy={busy} />}<Toast {...toast} onClose={() => setToast(null)} />
  </>;
}
